USE [master]
GO

/****** Object:  Database [COELSA_API]    Script Date: 27/1/2021 15:39:09 ******/
CREATE DATABASE [COELSA_API]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'COELSA_API', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.NOESQLEXPRESS\MSSQL\DATA\COELSA_API.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'COELSA_API_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.NOESQLEXPRESS\MSSQL\DATA\COELSA_API_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [COELSA_API].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [COELSA_API] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [COELSA_API] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [COELSA_API] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [COELSA_API] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [COELSA_API] SET ARITHABORT OFF 
GO

ALTER DATABASE [COELSA_API] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [COELSA_API] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [COELSA_API] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [COELSA_API] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [COELSA_API] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [COELSA_API] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [COELSA_API] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [COELSA_API] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [COELSA_API] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [COELSA_API] SET  DISABLE_BROKER 
GO

ALTER DATABASE [COELSA_API] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [COELSA_API] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [COELSA_API] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [COELSA_API] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [COELSA_API] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [COELSA_API] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [COELSA_API] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [COELSA_API] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [COELSA_API] SET  MULTI_USER 
GO

ALTER DATABASE [COELSA_API] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [COELSA_API] SET DB_CHAINING OFF 
GO

ALTER DATABASE [COELSA_API] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [COELSA_API] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [COELSA_API] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [COELSA_API] SET QUERY_STORE = OFF
GO

ALTER DATABASE [COELSA_API] SET  READ_WRITE 
GO


USE [COELSA_API]
GO

ALTER TABLE [dbo].[News] DROP CONSTRAINT [DF_News_updated_at]
GO

ALTER TABLE [dbo].[News] DROP CONSTRAINT [DF_News_created_at]
GO

/****** Object:  Table [dbo].[News]    Script Date: 27/1/2021 15:38:50 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[News]') AND type in (N'U'))
DROP TABLE [dbo].[News]
GO

/****** Object:  Table [dbo].[News]    Script Date: 27/1/2021 15:38:50 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[News](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[title] [varchar](250) NULL,
	[link] [varchar](255) NULL,
	[context] [varchar](max) NULL,
	[created_at] [datetime] NOT NULL,
	[updated_at] [datetime] NOT NULL,
 CONSTRAINT [PK_News] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[News] ADD  CONSTRAINT [DF_News_created_at]  DEFAULT (((1)/(1))/(1900)) FOR [created_at]
GO

ALTER TABLE [dbo].[News] ADD  CONSTRAINT [DF_News_updated_at]  DEFAULT (((1)/(1))/(1900)) FOR [updated_at]
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[Users]') AND type in (N'U'))
DROP TABLE [dbo].[Users]
GO

/****** Object:  Table [dbo].[Users]    Script Date: 27/1/2021 15:39:43 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Users](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[name] [varchar](150) NULL,
	[company] [varchar](150) NULL,
	[email] [varchar](250) NOT NULL,
	[password] [varchar](max) NULL,
	[role] [int] NOT NULL,
	[created_at] [datetime] NOT NULL,
	[updated_at] [datetime] NOT NULL,
 CONSTRAINT [PK_Users] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[Users] ADD  CONSTRAINT [DF_Users_role]  DEFAULT ((0)) FOR [role]
GO

ALTER TABLE [dbo].[Users] ADD  CONSTRAINT [DF_Users_created_at]  DEFAULT (((1)/(1))/(1900)) FOR [created_at]
GO

ALTER TABLE [dbo].[Users] ADD  CONSTRAINT [DF_Users_updated_at]  DEFAULT (((1)/(1))/(1900)) FOR [updated_at]
GO



