//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COELSAapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class New
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Link { get; set; }
        public string Context { get; set; }
        public System.DateTime Created_At { get; set; }
        public System.DateTime Updated_At { get; set; }
    }
}
